"""subo tablas ya cambiadas sin prioridad

Revision ID: 6510ea8d9728
Revises: 0b5475d58a2b
Create Date: 2026-02-24 09:03:10.980659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6510ea8d9728'
down_revision: Union[str, None] = '0b5475d58a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_categoria', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_table('zonas',
    sa.Column('id_zona', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_zona', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_zona')
    )
    op.create_table('estaciones',
    sa.Column('id_estacion', sa.String(length=20), nullable=False),
    sa.Column('id_zona', sa.Integer(), nullable=False),
    sa.Column('estado_actual', sa.Enum('DISPONIBLE', 'NO_DISPONIBLE', 'DISPONIBLE_CON_HALLAZGOS', name='estadoestacion'), nullable=True),
    sa.Column('sistema_operativo', sa.String(length=50), nullable=True),
    sa.Column('ultima_actualizacion', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_zona'], ['zonas.id_zona'], ),
    sa.PrimaryKeyConstraint('id_estacion')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('correo_institucional', sa.String(length=100), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=True),
    sa.Column('codigo_recuperacion', sa.String(length=6), nullable=True),
    sa.Column('fecha_expiracion_codigo', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo_institucional')
    )
    op.create_table('notificaciones',
    sa.Column('id_notificacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha_envio', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_table('tickets',
    sa.Column('id_ticket', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROCESO', 'RESUELTO', name='estadoticket'), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_usuario_creador', sa.Integer(), nullable=False),
    sa.Column('id_tecnico_asignado', sa.Integer(), nullable=True),
    sa.Column('id_estacion', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=True),
    sa.Column('fecha_resolucion', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_estacion'], ['estaciones.id_estacion'], ),
    sa.ForeignKeyConstraint(['id_tecnico_asignado'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_creador'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_ticket')
    )
    op.create_table('comentarios',
    sa.Column('id_comentario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('es_nota_interna', sa.Boolean(), nullable=True),
    sa.Column('evidencia_url', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_ticket'], ['tickets.id_ticket'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    op.drop_table('tickets')
    op.drop_table('notificaciones')
    op.drop_table('usuarios')
    op.drop_table('estaciones')
    op.drop_table('zonas')
    op.drop_table('roles')
    op.drop_table('categorias')
    # ### end Alembic commands ###
