"""subo tablas

Revision ID: bf4d1a1c2e6d
Revises: 
Create Date: 2026-05-21 12:17:10.661215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4d1a1c2e6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id_category', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('locations',
    sa.Column('id_location', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_location')
    )
    op.create_table('roles',
    sa.Column('id_role', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_role'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('floors',
    sa.Column('id_floor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('floor_name', sa.String(length=50), nullable=False),
    sa.Column('id_location', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_location'], ['locations.id_location'], ),
    sa.PrimaryKeyConstraint('id_floor')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('institutional_email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('campaign', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('recovery_code', sa.String(length=6), nullable=True),
    sa.Column('recovery_code_expiration', sa.TIMESTAMP(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('last_failed_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('locked_until', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id_role'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('institutional_email')
    )
    op.create_table('map_decorations',
    sa.Column('id_decoration', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_zone', sa.Integer(), nullable=False),
    sa.Column('decoration_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id_zone'], ['floors.id_floor'], ),
    sa.PrimaryKeyConstraint('id_decoration')
    )
    op.create_index(op.f('ix_map_decorations_id_zone'), 'map_decorations', ['id_zone'], unique=False)
    op.create_table('stations',
    sa.Column('id_station', sa.String(length=20), nullable=False),
    sa.Column('id_floor', sa.Integer(), nullable=False),
    sa.Column('id_zone', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.Enum('DISPONIBLE', 'NO_DISPONIBLE', 'DISPONIBLE_CON_HALLAZGOS', name='estadoestacion'), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_floor'], ['floors.id_floor'], ),
    sa.ForeignKeyConstraint(['id_zone'], ['floors.id_floor'], ),
    sa.PrimaryKeyConstraint('id_station')
    )
    op.create_index(op.f('ix_stations_id_zone'), 'stations', ['id_zone'], unique=False)
    op.create_table('tickets',
    sa.Column('id_ticket', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', name='estadoticket'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='priority'), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('primary_technician', sa.Integer(), nullable=True),
    sa.Column('secondary_technician', sa.Integer(), nullable=True),
    sa.Column('id_station', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('category_detail', sa.Text(), nullable=True),
    sa.Column('moved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['id_category'], ['categories.id_category'], ),
    sa.ForeignKeyConstraint(['id_station'], ['stations.id_station'], ),
    sa.ForeignKeyConstraint(['moved_by'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['primary_technician'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['secondary_technician'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_ticket')
    )
    op.create_table('changes_history',
    sa.Column('id_change', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('action_user', sa.Integer(), nullable=False),
    sa.Column('change_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['action_user'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['id_ticket'], ['tickets.id_ticket'], ),
    sa.PrimaryKeyConstraint('id_change')
    )
    op.create_table('comments',
    sa.Column('id_comment', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('internal_note', sa.Boolean(), nullable=True),
    sa.Column('evidence_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_ticket'], ['tickets.id_ticket'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_comment')
    )
    op.create_table('notifications',
    sa.Column('id_notification', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('id_ticket', sa.Integer(), nullable=True),
    sa.Column('id_station', sa.String(length=20), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_station'], ['stations.id_station'], ),
    sa.ForeignKeyConstraint(['id_ticket'], ['tickets.id_ticket'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_notification')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('comments')
    op.drop_table('changes_history')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_stations_id_zone'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_map_decorations_id_zone'), table_name='map_decorations')
    op.drop_table('map_decorations')
    op.drop_table('users')
    op.drop_table('floors')
    op.drop_table('roles')
    op.drop_table('locations')
    op.drop_table('categories')
    # ### end Alembic commands ###
